Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
==================== RESTART: C:/pythonne/pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:/pythonne/pybotbotdis.py", line 1, in <module>
    import discord
ImportError: No module named 'discord'
>>> 
==================== RESTART: C:/pythonne/pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:/pythonne/pybotbotdis.py", line 1, in <module>
    import discord
ImportError: No module named 'discord'
>>> 
==================== RESTART: C:/pythonne/pybotbotdis.py ====================
>>> 
Traceback (most recent call last):
  File "C:/pythonne/pybotbotdis.py", line 1, in <module>
    import discord
ImportError: No module named 'discord'
>>> 
==================== RESTART: C:/pythonne/pybotbotdis.py ====================
>>> 
Traceback (most recent call last):
  File "C:/pythonne/pybotbotdis.py", line 1, in <module>
    import discord
ImportError: No module named 'discord'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord
ImportError: No module named 'discord'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord.py
ImportError: No module named 'discord'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord.py
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 43, in <module>
    import websockets
ImportError: No module named 'websockets'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord.py
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 43, in <module>
    import websockets
ImportError: No module named 'websockets'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord.py
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 43, in <module>
    import websockets
ImportError: No module named 'websockets'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 43, in <module>
    import websockets
ImportError: No module named 'websockets'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord.py
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 43, in <module>
    import websockets
ImportError: No module named 'websockets'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
>>> 
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord.py
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 43, in <module>
    import websockets
ImportError: No module named 'websockets'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
>>> 
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 3, in <module>
    import discord.py
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 43, in <module>
    import websockets
ImportError: No module named 'websockets'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 2, in <module>
    import websockets
ImportError: No module named 'websockets'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================ImportError: No module named 'websockets'
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 5, in <module>
    import discord.py
ImportError: No module named 'discord.py'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 5, in <module>
    import discord.py
ImportError: No module named 'discord.py'
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 195, in static_login
    data = yield from self.get(self.ME)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 34, in <module>
    client.run('token')
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 487, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 387, in run_until_complete
    return future.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 458, in start
    yield from self.login(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 384, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 314, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 199, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 34, in <module>
    client.run(MjEwMDk4NTg5MDgxMjcyMzIw.CoJ1dw.xTAauN-GRTdvq_ccopLtxG3WGbI)
NameError: name 'MjEwMDk4NTg5MDgxMjcyMzIw' is not defined
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
Traceback (most recent call last):
  File "C:\pythonne\pybotbotdis.py", line 34, in <module>
    client.run(FYhkSOuN0lkr4G7EuocxE8FUA9E4jqh5)
NameError: name 'FYhkSOuN0lkr4G7EuocxE8FUA9E4jqh5' is not defined
>>> 
==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x030C9CB0>

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02E49CB0>

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02DC9CB0>
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 19, in on_ready
    server = await client.accept_invite('instantinvitecode')
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 2214, in accept_invite
    yield from self.http.accept_invite(invite_id)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 133, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Bots cannot use this endpoint

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02DC9CB0>
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 18, in on_ready
    server = await client.accept_invite('https://discord.gg/uMunU')
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 2214, in accept_invite
    yield from self.http.accept_invite(invite_id)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 133, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Bots cannot use this endpoint

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02DC9CB0>

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02DE9CB0>
<discord.message.Message object at 0x00386B70>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!sleep'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03871B70>
<discord.message.Message object at 0x038F7F30>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!sleep'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x038F7EB8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!sleep'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x02B22F30>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!sleep'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x02B22EB8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'

==================== RESTART: C:\pythonne\pybotbotdis.py ====================210098589081272320
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02DF9CB0>
<discord.message.Message object at 0x005F6BE8>
<discord.message.Message object at 0x02D72EB8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x02D72F30>
<discord.message.Message object at 0x03871B70>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03871C60>
<discord.message.Message object at 0x0395A030>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03871BE8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A6C0>
<discord.message.Message object at 0x0395A648>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A120>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A468>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A5D0>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A558>
<discord.message.Message object at 0x0395A300>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A198>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A378>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A738>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A4E0>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A828>
<discord.message.Message object at 0x0395A8A0>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AEB8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A288>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A0A8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AE40>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A210>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395ADC8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AF30>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AC60>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395ABE8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AB70>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395ACD8>
<discord.message.Message object at 0x0395A990>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AA08>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AA80>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AD50>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A918>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395AAF8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x0395A3F0>
<discord.message.Message object at 0x03983030>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983CD8>
<discord.message.Message object at 0x03983E40>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983F30>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983DC8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983120>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983EB8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983210>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983198>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983288>
<discord.message.Message object at 0x03983378>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983D50>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x039833F0>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983300>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983BE8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x039830A8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03983AF8>
<discord.message.Message object at 0x03983A08>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 31, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02E89CD0>
<discord.message.Message object at 0x02D92F30>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 23, in on_message
    if message.content.statswith('Привет, Никбот!'):
AttributeError: 'str' object has no attribute 'statswith'
<discord.message.Message object at 0x02D92EB8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 23, in on_message
    if message.content.statswith('Привет, Никбот!'):
AttributeError: 'str' object has no attribute 'statswith'

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02E69CF0>
<discord.message.Message object at 0x02DA2EB8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 23, in on_message
    if message.content.statswith('!Hi'):
AttributeError: 'str' object has no attribute 'statswith'
<discord.message.Message object at 0x02DA2F30>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 23, in on_message
    if message.content.statswith('!Hi'):
AttributeError: 'str' object has no attribute 'statswith'
<discord.message.Message object at 0x038B1BE8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 23, in on_message
    if message.content.statswith('!Hi'):
AttributeError: 'str' object has no attribute 'statswith'

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02E19CF0>
<discord.message.Message object at 0x02D92F30>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 34, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x02D92EB8>
<discord.message.Message object at 0x03881BE8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 34, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x03881B70>
<discord.message.Message object at 0x03A5E198>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 34, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 34, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02E79CF0>
<discord.message.Message object at 0x02D42F30>
<discord.message.Message object at 0x03872BE8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x02D42EB8>
<discord.message.Message object at 0x03872B70>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02E29CF0>
<discord.message.Message object at 0x02DA2F30>
<discord.message.Message object at 0x038A1BE8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02E19CD0>
<discord.message.Message object at 0x02D42EB8>
<discord.message.Message object at 0x03872BE8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
<discord.message.Message object at 0x02D42F30>
<discord.message.Message object at 0x03872CD8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\pythonne\pybotbotdis.py", line 35, in on_message
    elif message.content.startwith('!s'):
AttributeError: 'str' object has no attribute 'startwith'

==================== RESTART: C:\pythonne\pybotbotdis.py ====================
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:on_ready has successfully been registered as an event
INFO:discord.client:on_message has successfully been registered as an event
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
Logged in as
Nicbot
210098589081272320
-----
<discord.client.Client object at 0x02E49CD0>
